/* Addon Forge seed index.
 *
 * Every entry here is a real, genuinely free addon, plugin or package, checked
 * by hand on the date in INDEX.checked. No entry is invented and no count is
 * padded: the engine totals are simply how many were found, which is why the
 * lanes are uneven. That unevenness is the point.
 *
 * "licence" is the licence the project itself publishes. Where a project is
 * free but does not publish a clear SPDX licence, it is not listed here at all.
 */

const ENGINES = [
  { id: "blender", name: "Blender",       hue: "#EA7600", short: "BLN" },
  { id: "unreal",  name: "Unreal Engine", hue: "#8FA8C4", short: "UE5" },
  { id: "unity",   name: "Unity",         hue: "#E8E8ED", short: "UNI" },
  { id: "daz",     name: "Daz Studio",    hue: "#2A9D8F", short: "DAZ" }
];

const INDEX = {
  checked: "2026-09-17",
  sources: 4,
  items: [
    /* ---- Blender -------------------------------------------------------- */
    { engine: "blender", name: "Node Wrangler", licence: "GPL-2.0", host: "blender.org", bundled: true,
      url: "https://docs.blender.org/manual/en/latest/addons/node/node_wrangler.html",
      tags: ["nodes", "shading", "workflow"],
      note: "Keyboard shortcuts for building shader and geometry node trees." },
    { engine: "blender", name: "Bool Tool", licence: "GPL-2.0", host: "blender.org", bundled: true,
      url: "https://docs.blender.org/manual/en/latest/addons/object/bool_tool.html",
      tags: ["boolean", "hard surface", "modelling"],
      note: "Boolean operations bound to shortcuts, with a live brush mode." },
    { engine: "blender", name: "LoopTools", licence: "GPL-2.0", host: "blender.org", bundled: true,
      url: "https://docs.blender.org/manual/en/latest/addons/mesh/looptools.html",
      tags: ["mesh", "retopology", "modelling"],
      note: "Relax, space, circle, flatten and bridge operations on edge loops." },
    { engine: "blender", name: "Rigify", licence: "GPL-2.0", host: "blender.org", bundled: true,
      url: "https://docs.blender.org/manual/en/latest/addons/rigging/rigify/index.html",
      tags: ["rigging", "animation", "armature"],
      note: "Modular auto rigging. Builds a full control rig from a metarig." },
    { engine: "blender", name: "Add Mesh Extra Objects", licence: "GPL-2.0", host: "blender.org", bundled: true,
      url: "https://docs.blender.org/manual/en/latest/addons/add_mesh/mesh_extra_objects.html",
      tags: ["primitives", "modelling"],
      note: "Extra primitives: gears, pipes, rocks, maths surfaces, gemstones." },
    { engine: "blender", name: "Import Images as Planes", licence: "GPL-2.0", host: "blender.org", bundled: true,
      url: "https://docs.blender.org/manual/en/latest/addons/import_export/images_as_planes.html",
      tags: ["import", "reference", "texture"],
      note: "Drops images into the scene as correctly sized textured planes." },
    { engine: "blender", name: "MeasureIt", licence: "GPL-2.0", host: "blender.org", bundled: true,
      url: "https://docs.blender.org/manual/en/latest/addons/3d_view/measureit.html",
      tags: ["measurement", "architecture", "cad"],
      note: "Dimension lines and annotations drawn in the viewport and renders." },
    { engine: "blender", name: "Archimesh", licence: "GPL-2.0", host: "blender.org", bundled: true,
      url: "https://docs.blender.org/manual/en/latest/addons/add_mesh/archimesh.html",
      tags: ["architecture", "interior"],
      note: "Parametric rooms, doors, windows, stairs and furniture." },
    { engine: "blender", name: "Cell Fracture", licence: "GPL-2.0", host: "blender.org", bundled: true,
      url: "https://docs.blender.org/manual/en/latest/addons/object/cell_fracture.html",
      tags: ["destruction", "simulation", "vfx"],
      note: "Splits a mesh into cells for shattering and destruction sims." },
    { engine: "blender", name: "F2", licence: "GPL-2.0", host: "blender.org", bundled: true,
      url: "https://docs.blender.org/manual/en/latest/addons/mesh/f2.html",
      tags: ["mesh", "modelling"],
      note: "Extends the F key to build faces from a single vertex." },
    { engine: "blender", name: "Sverchok", licence: "GPL-3.0", host: "github.com",
      url: "https://github.com/nortikin/sverchok",
      tags: ["parametric", "nodes", "cad", "procedural"],
      note: "Node based parametric modelling, in the lineage of Grasshopper." },
    { engine: "blender", name: "Animation Nodes", licence: "GPL-3.0", host: "github.com",
      url: "https://github.com/JacquesLucke/animation_nodes",
      tags: ["motion graphics", "nodes", "procedural"],
      note: "Node system for procedural animation and motion graphics." },
    { engine: "blender", name: "MACHIN3tools", licence: "GPL-3.0", host: "github.com",
      url: "https://github.com/machin3io/MACHIN3tools",
      tags: ["hard surface", "workflow", "modelling"],
      note: "A large free workflow and hard surface toolset with pie menus." },
    { engine: "blender", name: "Molecular Nodes", licence: "GPL-3.0", host: "github.com",
      url: "https://github.com/BradyAJohnston/MolecularNodes",
      tags: ["scientific", "geometry nodes", "visualisation"],
      note: "Imports and renders molecular and structural biology data." },
    { engine: "blender", name: "Tissue", licence: "GPL-3.0", host: "github.com",
      url: "https://github.com/alessandro-zomparelli/tissue",
      tags: ["parametric", "tessellation", "computational"],
      note: "Computational design: tessellation, reaction diffusion, contouring." },
    { engine: "blender", name: "MB-Lab", licence: "AGPL-3.0", host: "github.com",
      url: "https://github.com/animate1978/MB-Lab",
      tags: ["character", "human", "parametric"],
      note: "Parametric human character generator with rigged output." },

    /* ---- Unreal Engine --------------------------------------------------- */
    { engine: "unreal", name: "Open Unreal Utilities", licence: "MIT", host: "github.com",
      url: "https://github.com/JonasReich/OpenUnrealUtilities",
      tags: ["utilities", "gameplay", "ui"],
      note: "General purpose gameplay, UI and developer utility library." },
    { engine: "unreal", name: "Async Loading Screen", licence: "MIT", host: "github.com",
      url: "https://github.com/truong-bui/AsyncLoadingScreen",
      tags: ["loading", "ui", "streaming"],
      note: "Adds a loading screen on level open without level streaming." },
    { engine: "unreal", name: "Runtime Audio Importer", licence: "MIT", host: "github.com",
      url: "https://github.com/gtreshchev/RuntimeAudioImporter",
      tags: ["audio", "runtime", "import"],
      note: "Imports audio in several formats at runtime, no cook step." },
    { engine: "unreal", name: "Realtime Mesh Component", licence: "MIT", host: "github.com",
      url: "https://github.com/TriAxis-Games/RealtimeMeshComponent",
      tags: ["procedural", "mesh", "runtime"],
      note: "Renders runtime generated geometry. Core component is MIT." },
    { engine: "unreal", name: "Unreal ImGui", licence: "MIT", host: "github.com",
      url: "https://github.com/segross/UnrealImGui",
      tags: ["debug", "tooling", "ui"],
      note: "Integrates Dear ImGui for in-engine debug interfaces." },
    { engine: "unreal", name: "Mountea Dialogue System", licence: "MIT", host: "github.com",
      url: "https://github.com/Mountea-Framework/MounteaDialogueSystem",
      tags: ["dialogue", "narrative", "editor"],
      note: "Dialogue trees with a dedicated editor and validation pass." },
    { engine: "unreal", name: "Procedural Dungeon", licence: "MIT", host: "github.com",
      url: "https://github.com/BenPyton/ProceduralDungeon",
      tags: ["procedural", "level generation"],
      note: "Room based procedural dungeon generation for UE4 and UE5." },

    /* ---- Unity ----------------------------------------------------------- */
    { engine: "unity", name: "ProBuilder", licence: "Unity Companion", host: "unity3d.com", bundled: true,
      url: "https://docs.unity3d.com/Packages/com.unity.probuilder@latest",
      tags: ["modelling", "level design", "greybox"],
      note: "In-editor mesh modelling and level blockout." },
    { engine: "unity", name: "Cinemachine", licence: "Unity Companion", host: "unity3d.com", bundled: true,
      url: "https://docs.unity3d.com/Packages/com.unity.cinemachine@latest",
      tags: ["camera", "cinematics", "animation"],
      note: "Procedural camera rigs, blends and shot composition." },
    { engine: "unity", name: "Shader Graph", licence: "Unity Companion", host: "unity3d.com", bundled: true,
      url: "https://docs.unity3d.com/Packages/com.unity.shadergraph@latest",
      tags: ["shaders", "nodes", "visual"],
      note: "Node based shader authoring for the scriptable render pipelines." },
    { engine: "unity", name: "TextMesh Pro", licence: "Unity Companion", host: "unity3d.com", bundled: true,
      url: "https://docs.unity3d.com/Packages/com.unity.textmeshpro@latest",
      tags: ["text", "ui", "typography"],
      note: "Signed distance field text rendering and layout." },
    { engine: "unity", name: "Polybrush", licence: "Unity Companion", host: "unity3d.com", bundled: true,
      url: "https://docs.unity3d.com/Packages/com.unity.polybrush@latest",
      tags: ["sculpting", "vertex paint", "scatter"],
      note: "Sculpt, paint vertex colours and scatter meshes in the editor." },
    { engine: "unity", name: "Unity Recorder", licence: "Unity Companion", host: "unity3d.com", bundled: true,
      url: "https://docs.unity3d.com/Packages/com.unity.recorder@latest",
      tags: ["capture", "video", "render"],
      note: "Captures video, image sequences and animation from play mode." },
    { engine: "unity", name: "UniTask", licence: "MIT", host: "github.com",
      url: "https://github.com/Cysharp/UniTask",
      tags: ["async", "performance", "c#"],
      note: "Allocation free async and await integration for Unity." },
    { engine: "unity", name: "UniRx", licence: "MIT", host: "github.com",
      url: "https://github.com/neuecc/UniRx",
      tags: ["reactive", "events", "c#"],
      note: "Reactive Extensions for Unity: observable event composition." },
    { engine: "unity", name: "NaughtyAttributes", licence: "MIT", host: "github.com",
      url: "https://github.com/dbrizov/NaughtyAttributes",
      tags: ["inspector", "editor", "attributes"],
      note: "Inspector attributes without writing custom property drawers." },
    { engine: "unity", name: "Newtonsoft Json for Unity", licence: "MIT", host: "unity3d.com", bundled: true,
      url: "https://docs.unity3d.com/Packages/com.unity.nuget.newtonsoft-json@latest",
      tags: ["json", "serialisation", "c#"],
      note: "Unity packaged build of Json.NET." },

    /* ---- Daz Studio ------------------------------------------------------ */
    { engine: "daz", name: "Daz To Blender", licence: "Apache-2.0", host: "github.com",
      url: "https://github.com/daz3d/DazToBlender",
      tags: ["bridge", "export", "blender"],
      note: "Official bridge. Exports figures and materials into Blender." },
    { engine: "daz", name: "Daz To Unreal", licence: "Apache-2.0", host: "github.com",
      url: "https://github.com/daz3d/DazToUnreal",
      tags: ["bridge", "export", "unreal"],
      note: "Official bridge. Exports figures and materials into Unreal." },
    { engine: "daz", name: "Daz To Unity", licence: "Apache-2.0", host: "github.com",
      url: "https://github.com/daz3d/DazToUnity",
      tags: ["bridge", "export", "unity"],
      note: "Official bridge. Exports figures and materials into Unity." },
    { engine: "daz", name: "Daz To Maya", licence: "Apache-2.0", host: "github.com",
      url: "https://github.com/daz3d/DazToMaya",
      tags: ["bridge", "export", "maya"],
      note: "Official bridge. Exports figures and materials into Maya." },
    { engine: "daz", name: "Daz To 3ds Max", licence: "Apache-2.0", host: "github.com",
      url: "https://github.com/daz3d/DazTo3dsMax",
      tags: ["bridge", "export", "3ds max"],
      note: "Official bridge. Exports figures and materials into 3ds Max." },
    { engine: "daz", name: "Daz Bridge Library", licence: "Apache-2.0", host: "github.com",
      url: "https://github.com/daz3d/DazBridgeUtils",
      tags: ["bridge", "library", "shared"],
      note: "Shared foundation the official bridges are all built on." }
  ]
};

INDEX.items.forEach((it, i) => { it.id = String(i + 1).padStart(3, "0"); });
